services:
  mysql:
    image: mysql:8.4
    container_name: gestion_proveedores_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=gestion_proveedores
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data: